Repository RedJunHee/StoreReview, pull requests merged in 2021-12, with the labels that each got.

#2 model: Review, Comment, Log 생성
  build.gradle
  src/main/java/com/review/StoreReview/StoreReviewApplication.java
  src/main/java/com/review/StoreReview/common/BaseTimeEntity.java
  src/main/java/com/review/StoreReview/domain/comment/Comment.java
  src/main/java/com/review/StoreReview/domain/log/Log.java
  src/main/java/com/review/StoreReview/domain/review/Review.java
  src/main/java/com/review/StoreReview/domain/user/User.java
  src/main/resources/application.yml
Labels: good first issue

#5 객체 및 패키지 수정
  src/main/java/com/review/StoreReview/domain/Comment.java
  src/main/java/com/review/StoreReview/domain/Log.java
  src/main/java/com/review/StoreReview/domain/MngCode.java
  src/main/java/com/review/StoreReview/domain/MngCodeInfo.java
  src/main/java/com/review/StoreReview/domain/Review.java
  src/main/java/com/review/StoreReview/domain/User.java
Labels: enhancement

#7 ApiStatusCode 추가 및 AOP 객체 개발중
  src/main/java/com/review/StoreReview/common/ApiStatusCode.java
  src/main/java/com/review/StoreReview/common/impl/KeyValueEnumImpl.java
  src/main/java/com/review/StoreReview/domain/MngCode.java
  src/main/java/com/review/StoreReview/domain/MngCodeInfo.java
  src/main/java/com/review/StoreReview/domain/User.java
  src/main/java/com/review/StoreReview/web/aop/RqeustAroundLogAop.java
  src/main/java/com/review/StoreReview/web/rest/controller/dto/CommonResDto.java
  src/test/java/com/review/StoreReview/common/ApiStatusCodeTest.java
Labels: enhancement

#8 MVC, RequestDto, JPAConfig 추가
  .gitignore
  src/main/java/com/review/StoreReview/config/CMSJpaConfig.java
  src/main/java/com/review/StoreReview/config/CUSTJpaConfig.java
  src/main/java/com/review/StoreReview/config/LOGJpaConfig.java
  src/main/java/com/review/StoreReview/config/MNGJpaConfig.java
  src/main/java/com/review/StoreReview/domain/MNG/MngCodeInfo.java
  src/main/java/com/review/StoreReview/service/UserServiceImpl.java
  src/main/java/com/review/StoreReview/web/rest/controller/dto/UserSaveRequestDto.java
  src/main/resources/application.yml
Labels: help wanted

#11 JPAConfig 수정 및 에러 해결
  src/main/java/com/review/StoreReview/StoreReviewApplication.java
  src/main/java/com/review/StoreReview/config/CMSJpaConfig.java
  src/main/java/com/review/StoreReview/config/LOGJpaConfig.java
  src/main/java/com/review/StoreReview/config/MNGJpaConfig.java
  src/main/java/com/review/StoreReview/domain/MNG/MngCode.java
Labels: enhancement
