Repository RedJunHee/StoreReview, pull requests merged in 2022-01, with the labels that each got.

#29 Revert "Refactoring/부가수정"
  src/main/java/com/review/storereview/common/AppConfig.java
  src/main/java/com/review/storereview/controller/cust/UserApiController.java
  src/main/java/com/review/storereview/dao/cust/User.java
  src/main/java/com/review/storereview/dto/request/UserSaveRequestDto.java
  src/main/java/com/review/storereview/dto/response/UserResponseDto.java
  src/main/java/com/review/storereview/repository/cust/BaseUserRepository.java
  src/main/java/com/review/storereview/service/cust/UserServiceImpl.java
  src/main/resources/application.yml
Labels: 리팩토링

#31 UserSaveDtoValidator와 MockMvc 테스트코드 추가
  src/main/java/com/review/storereview/common/AppConfig.java
  src/main/java/com/review/storereview/common/exception/ParamValidationException.java
  src/main/java/com/review/storereview/controller/cust/UserApiController.java
  src/main/java/com/review/storereview/dao/cust/User.java
  src/main/java/com/review/storereview/dto/response/UserResponseDto.java
  src/main/java/com/review/storereview/dto/validator/UserSaveDtoValidator.java
  src/main/java/com/review/storereview/repository/cust/BaseUserRepository.java
  src/main/java/com/review/storereview/service/cust/BaseUserService.java
  src/main/java/com/review/storereview/service/cust/UserServiceImpl.java
  src/test/java/com/review/storereview/common/exception/handler/GlobalExceptionHandlerTest.java
  src/test/java/com/review/storereview/controller/cust/UserApiControllerTest.java
  src/test/java/com/review/storereview/repository/cust/BaseUserRepositoryTest.java
  src/test/java/com/review/storereview/service/cust/UserServiceImplTest.java
Labels: 개선 필요

#32 Security JWT 인증/인가 기능 개발.
  build.gradle
  src/main/java/com/review/storereview/StoreReviewApplication.java
  src/main/java/com/review/storereview/common/AppConfig.java
  src/main/java/com/review/storereview/common/JwtTokenProvider.java
  src/main/java/com/review/storereview/common/WebSecurityConfig.java
  src/main/java/com/review/storereview/common/enumerate/Authority.java
  src/main/java/com/review/storereview/common/exception/CustomAuthenticationException.java
  src/main/java/com/review/storereview/common/exception/CustomAuthorizationException.java
  src/main/java/com/review/storereview/common/exception/handler/AuthenticationExceptionHandler.java
  src/main/java/com/review/storereview/common/exception/handler/AuthorizationExceptionHandler.java
  src/main/java/com/review/storereview/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/review/storereview/config/SecurityConfig.java
  src/main/java/com/review/storereview/controller/TestController.java
  src/main/java/com/review/storereview/controller/cust/AuthController.java
  src/main/java/com/review/storereview/controller/cust/UserApiController.java
  src/main/java/com/review/storereview/dto/request/TokenDto.java
  src/main/java/com/review/storereview/dto/request/UserSaveRequestDto.java
  src/main/java/com/review/storereview/dto/request/UserSigninRequestDto.java
  src/main/java/com/review/storereview/dto/response/UserResponseDto.java
  src/main/java/com/review/storereview/filter/AuthorizationCheckFilter.java
  src/main/java/com/review/storereview/repository/cust/BaseUserRepository.java
  src/main/java/com/review/storereview/service/cust/AuthService.java
  src/main/java/com/review/storereview/service/cust/UserServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/review/storereview/ReviewServiceApplicationTests.java
  src/test/java/com/review/storereview/controller/cust/AbstractControllerTest.java
  src/test/java/com/review/storereview/controller/cust/AuthControllerTest.java
Labels: 개발, 질문, 개선 필요

#34 Refactoring/부가수정 및 encode 추가
  src/main/java/com/review/storereview/aop/RequestAroundLogAop.java
  src/main/java/com/review/storereview/common/JwtTokenProvider.java
  src/main/java/com/review/storereview/common/exception/CustomAuthenticationException.java
  src/main/java/com/review/storereview/common/exception/CustomAuthorizationException.java
  src/main/java/com/review/storereview/common/exception/ParamValidationException.java
  src/main/java/com/review/storereview/common/exception/PersonAlreadyExistsException.java
  src/main/java/com/review/storereview/common/exception/PersonNotFoundException.java
  src/main/java/com/review/storereview/common/exception/dto/ExceptionResponseDto.java
  src/main/java/com/review/storereview/common/exception/handler/AuthenticationExceptionHandler.java
  src/main/java/com/review/storereview/common/exception/handler/AuthorizationExceptionHandler.java
  src/main/java/com/review/storereview/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/review/storereview/common/utils/CryptUtils.java
  src/main/java/com/review/storereview/config/SecurityConfig.java
  src/main/java/com/review/storereview/controller/cust/AuthController.java
  src/main/java/com/review/storereview/controller/cust/UserApiController.java
  src/main/java/com/review/storereview/dao/cust/User.java
  src/main/java/com/review/storereview/dto/ResponseJsonObject.java
  src/main/java/com/review/storereview/dto/request/UserSaveRequestDto.java
  src/main/java/com/review/storereview/dto/validator/UserSaveDtoValidator.java
  src/main/java/com/review/storereview/filter/AuthorizationCheckFilter.java
  src/main/java/com/review/storereview/service/cust/BaseUserService.java
  src/main/java/com/review/storereview/service/cust/UserServiceImpl.java
  src/main/java/com/review/storereview/service/log/LogService.java
  src/test/java/com/review/storereview/common/exception/ParamValidationExceptionTest.java
  src/test/java/com/review/storereview/controller/cust/UserApiControllerTest.java
  src/test/java/com/review/storereview/dto/ResponseJsonObjectTest.java
  src/test/java/com/review/storereview/dto/response/UserResponseDtoTest.java
  src/test/java/com/review/storereview/repository/cust/BaseUserRepositoryTest.java
  src/test/java/com/review/storereview/service/cust/UserServiceImplTest.java
Labels: 리팩토링, 개선 필요

#35 REVIEW API 개발 1차 완료
  src/main/java/com/review/storereview/common/enumerate/ApiStatusCode.java
  src/main/java/com/review/storereview/common/exception/ReviewNotFoundException.java
  src/main/java/com/review/storereview/common/utils/StringListConverter.java
  src/main/java/com/review/storereview/controller/cms/ReviewApiController.java
  src/main/java/com/review/storereview/controller/cust/UserApiController.java
  src/main/java/com/review/storereview/dao/BaseTimeEntity.java
  src/main/java/com/review/storereview/dao/cms/Review.java
  src/main/java/com/review/storereview/dto/request/ReviewUpdateRequestDto.java
  src/main/java/com/review/storereview/dto/request/ReviewUploadRequestDto.java
  src/main/java/com/review/storereview/dto/response/ReviewResponseDto.java
  src/main/java/com/review/storereview/dto/validator/UserSaveDtoValidator.java
  src/main/java/com/review/storereview/repository/cms/BaseReviewRepository.java
  src/main/java/com/review/storereview/repository/cust/BaseUserRepository.java
  src/main/java/com/review/storereview/service/cms/ReviewServiceImpl.java
  src/main/java/com/review/storereview/service/cust/BaseUserService.java
  src/main/java/com/review/storereview/service/cust/UserServiceImpl.java
Labels: 개선 필요

#37 SUID, SAID 생성 로직 추가
  src/main/java/com/review/storereview/controller/cms/ReviewApiController.java
  src/main/java/com/review/storereview/dao/cms/Review.java
  src/main/java/com/review/storereview/dto/request/ReviewUploadRequestDto.java
  src/main/java/com/review/storereview/dto/request/UserSaveRequestDto.java
  src/main/java/com/review/storereview/repository/cms/BaseReviewRepository.java
  src/main/java/com/review/storereview/service/cms/ReviewServiceImpl.java
  src/main/java/com/review/storereview/service/cust/BaseUserService.java
  src/main/java/com/review/storereview/service/cust/UserServiceImpl.java
  src/test/java/com/review/storereview/controller/cust/UserApiControllerTest.java
  src/test/java/com/review/storereview/repository/cust/BaseUserRepositoryTest.java
  src/test/java/com/review/storereview/service/cms/ReviewServiceImplTest.java
  src/test/java/com/review/storereview/service/cust/UserServiceImplTest.java
Labels: 개선 필요
